version: "3.1"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRESPASSWORD: ${DB_PASSWORD}
      - POSTGRESUSER: ${DB_USER}
      - POSTGRESDB: ${DB_NAME}
    ports:
      - ${DB_PORT}: 5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
